/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_JniUtil */

#ifndef _Included_com_example_ffmpeg_JniUtil
#define _Included_com_example_ffmpeg_JniUtil

extern "C"
JNIEXPORT void JNICALL
Java_com_example_ffmpeg_JniUtil_meta(JNIEnv *env, jobject instance, jstring path_) {
    const char *path = env->GetStringUTFChars(path_, 0);

    // TODO

    env->ReleaseStringUTFChars(path_, path);
}

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_JniUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_JniUtil_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ffmpeg_JniUtil
 * Method:    newFum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ffmpeg_JniUtil_newFum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
